### ISSUE TITLE
Publish StructuredText as package

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/head-start#93]
The [`StructuredText` component](https://github.com/voorhoede/head-start/tree/main/src/components/StructuredText) is generic and could be published as a separate package. 

Also see [Astro: publish to npm](https://docs.astro.build/en/reference/publish-to-npm/).

**Comment by jbmoelker** [comment]
@Siilwyn is this something you'd be interested in doing or guiding as part of our Open Source efforts?

**Comment by Siilwyn** [comment]
Yes I am! Just need some time :)

**Comment by jbmoelker** [comment]
DatoCMS beat us to it! https://github.com/datocms/astro-datocms/tree/main/src/StructuredText

So we should see if we can use that package instead
